import { Exercise } from "./types";

export const exercises: Record<string, Exercise[]> = {
    chest: [
      {
        id: "bench-press",
        name: "Bench Press",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Chest"],
        secondaryMuscles: ["Shoulders", "Triceps"],
        duration: "45 min",
      },
      {
        id: "push-ups",
        name: "Push-ups",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Chest"],
        secondaryMuscles: ["Shoulders", "Triceps"],
        duration: "20 min",
      },
      {
        id: "dumbbell-flyes",
        name: "Dumbbell Flyes",
        difficulty: "intermediate",
        equipment: "Dumbbells",
        primaryMuscles: ["Chest"],
        secondaryMuscles: ["Shoulders"],
        duration: "30 min",
      },
      {
        id: "incline-bench-press",
        name: "Incline Bench Press",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Chest"],
        secondaryMuscles: ["Shoulders", "Triceps"],
        duration: "40 min",
      },
      {
        id: "decline-bench-press",
        name: "Decline Bench Press",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Chest"],
        secondaryMuscles: ["Shoulders", "Triceps"],
        duration: "40 min",
      },
      {
        id: "chest-dips",
        name: "Chest Dips",
        difficulty: "intermediate",
        equipment: "Bodyweight",
        primaryMuscles: ["Chest"],
        secondaryMuscles: ["Shoulders", "Triceps"],
        duration: "25 min",
      },
    ],
    shoulders: [
      {
        id: "overhead-press",
        name: "Overhead Press",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Shoulders"],
        secondaryMuscles: ["Triceps", "Core"],
        duration: "40 min",
      },
      {
        id: "lateral-raises",
        name: "Lateral Raises",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Shoulders"],
        secondaryMuscles: [],
        duration: "25 min",
      },
      {
        id: "front-raises",
        name: "Front Raises",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Shoulders"],
        secondaryMuscles: [],
        duration: "25 min",
      },
      {
        id: "rear-delt-flyes",
        name: "Rear Delt Flyes",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Shoulders"],
        secondaryMuscles: ["Trapezius"],
        duration: "25 min",
      },
      {
        id: "arnold-press",
        name: "Arnold Press",
        difficulty: "intermediate",
        equipment: "Dumbbells",
        primaryMuscles: ["Shoulders"],
        secondaryMuscles: ["Triceps"],
        duration: "30 min",
      },
    ],
    biceps: [
      {
        id: "bicep-curls",
        name: "Bicep Curls",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Biceps"],
        secondaryMuscles: ["Forearms"],
        duration: "25 min",
      },
      {
        id: "hammer-curls",
        name: "Hammer Curls",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Biceps"],
        secondaryMuscles: ["Forearms"],
        duration: "25 min",
      },
      {
        id: "preacher-curls",
        name: "Preacher Curls",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Biceps"],
        secondaryMuscles: ["Forearms"],
        duration: "30 min",
      },
      {
        id: "concentration-curls",
        name: "Concentration Curls",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Biceps"],
        secondaryMuscles: ["Forearms"],
        duration: "25 min",
      },
    ],
    abs: [
      {
        id: "crunches",
        name: "Crunches",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Abs"],
        secondaryMuscles: [],
        duration: "15 min",
      },
      {
        id: "plank",
        name: "Plank",
        difficulty: "intermediate",
        equipment: "Bodyweight",
        primaryMuscles: ["Abs"],
        secondaryMuscles: ["Shoulders", "Back"],
        duration: "10 min",
      },
      {
        id: "bicycle-crunches",
        name: "Bicycle Crunches",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Abs"],
        secondaryMuscles: ["Obliques"],
        duration: "15 min",
      },
      {
        id: "leg-raises",
        name: "Leg Raises",
        difficulty: "intermediate",
        equipment: "Bodyweight",
        primaryMuscles: ["Abs"],
        secondaryMuscles: ["Hip Flexors"],
        duration: "20 min",
      },
      {
        id: "mountain-climbers",
        name: "Mountain Climbers",
        difficulty: "intermediate",
        equipment: "Bodyweight",
        primaryMuscles: ["Abs"],
        secondaryMuscles: ["Shoulders", "Legs"],
        duration: "15 min",
      },
    ],
    // NEW: Obliques section
    obliques: [
      {
        id: "russian-twists",
        name: "Russian Twists",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Obliques"],
        secondaryMuscles: ["Abs"],
        duration: "15 min",
      },
      {
        id: "side-planks",
        name: "Side Planks",
        difficulty: "intermediate",
        equipment: "Bodyweight",
        primaryMuscles: ["Obliques"],
        secondaryMuscles: ["Abs", "Shoulders"],
        duration: "15 min",
      },
      {
        id: "wood-choppers",
        name: "Wood Choppers",
        difficulty: "intermediate",
        equipment: "Cable Machine",
        primaryMuscles: ["Obliques"],
        secondaryMuscles: ["Abs", "Shoulders"],
        duration: "25 min",
      },
      {
        id: "side-bends",
        name: "Dumbbell Side Bends",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Obliques"],
        secondaryMuscles: ["Abs"],
        duration: "20 min",
      },
      {
        id: "bicycle-kicks",
        name: "Bicycle Kicks",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Obliques"],
        secondaryMuscles: ["Abs"],
        duration: "15 min",
      },
      {
        id: "hanging-knee-raises-oblique",
        name: "Hanging Oblique Knee Raises",
        difficulty: "advanced",
        equipment: "Pull-up Bar",
        primaryMuscles: ["Obliques"],
        secondaryMuscles: ["Abs", "Forearms"],
        duration: "20 min",
      },
    ],
    // NEW: Forearms section
    forearms: [
      {
        id: "wrist-curls",
        name: "Wrist Curls",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Forearms"],
        secondaryMuscles: [],
        duration: "20 min",
      },
      {
        id: "reverse-wrist-curls",
        name: "Reverse Wrist Curls",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Forearms"],
        secondaryMuscles: [],
        duration: "20 min",
      },
      {
        id: "farmers-walk",
        name: "Farmer's Walk",
        difficulty: "intermediate",
        equipment: "Dumbbells",
        primaryMuscles: ["Forearms"],
        secondaryMuscles: ["Trapezius", "Core"],
        duration: "15 min",
      },
      {
        id: "plate-pinches",
        name: "Plate Pinches",
        difficulty: "intermediate",
        equipment: "Weight Plates",
        primaryMuscles: ["Forearms"],
        secondaryMuscles: [],
        duration: "15 min",
      },
      {
        id: "grip-crushers",
        name: "Grip Crushers",
        difficulty: "beginner",
        equipment: "Grip Trainer",
        primaryMuscles: ["Forearms"],
        secondaryMuscles: [],
        duration: "15 min",
      },
      {
        id: "dead-hangs",
        name: "Dead Hangs",
        difficulty: "intermediate",
        equipment: "Pull-up Bar",
        primaryMuscles: ["Forearms"],
        secondaryMuscles: ["Lats"],
        duration: "10 min",
      },
    ],
    quads: [
      {
        id: "squats",
        name: "Squats",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes", "Hamstrings"],
        duration: "45 min",
      },
      {
        id: "lunges",
        name: "Lunges",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes", "Calves"],
        duration: "30 min",
      },
      {
        id: "leg-press",
        name: "Leg Press",
        difficulty: "beginner",
        equipment: "Machine",
        primaryMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes"],
        duration: "35 min",
      },
      {
        id: "leg-extensions",
        name: "Leg Extensions",
        difficulty: "beginner",
        equipment: "Machine",
        primaryMuscles: ["Quadriceps"],
        secondaryMuscles: [],
        duration: "25 min",
      },
      {
        id: "bulgarian-split-squats",
        name: "Bulgarian Split Squats",
        difficulty: "intermediate",
        equipment: "Bodyweight",
        primaryMuscles: ["Quadriceps"],
        secondaryMuscles: ["Glutes"],
        duration: "30 min",
      },
    ],
    calves: [
      {
        id: "calf-raises",
        name: "Calf Raises",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Calves"],
        secondaryMuscles: [],
        duration: "20 min",
      },
      {
        id: "seated-calf-raises",
        name: "Seated Calf Raises",
        difficulty: "beginner",
        equipment: "Machine",
        primaryMuscles: ["Calves"],
        secondaryMuscles: [],
        duration: "25 min",
      },
      {
        id: "donkey-calf-raises",
        name: "Donkey Calf Raises",
        difficulty: "intermediate",
        equipment: "Machine",
        primaryMuscles: ["Calves"],
        secondaryMuscles: [],
        duration: "25 min",
      },
    ],
    traps: [
      {
        id: "shrugs",
        name: "Barbell Shrugs",
        difficulty: "beginner",
        equipment: "Barbell",
        primaryMuscles: ["Trapezius"],
        secondaryMuscles: ["Shoulders"],
        duration: "20 min",
      },
      {
        id: "upright-rows",
        name: "Upright Rows",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Trapezius"],
        secondaryMuscles: ["Shoulders", "Biceps"],
        duration: "25 min",
      },
      {
        id: "dumbbell-shrugs",
        name: "Dumbbell Shrugs",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Trapezius"],
        secondaryMuscles: ["Shoulders"],
        duration: "20 min",
      },
      {
        id: "face-pulls",
        name: "Face Pulls",
        difficulty: "beginner",
        equipment: "Cable Machine",
        primaryMuscles: ["Trapezius"],
        secondaryMuscles: ["Shoulders"],
        duration: "20 min",
      },
    ],
    lats: [
      {
        id: "pull-ups",
        name: "Pull-ups",
        difficulty: "intermediate",
        equipment: "Bodyweight",
        primaryMuscles: ["Latissimus Dorsi"],
        secondaryMuscles: ["Biceps", "Trapezius"],
        duration: "30 min",
      },
      {
        id: "barbell-rows",
        name: "Barbell Rows",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Latissimus Dorsi"],
        secondaryMuscles: ["Trapezius", "Biceps"],
        duration: "35 min",
      },
      {
        id: "lat-pulldowns",
        name: "Lat Pulldowns",
        difficulty: "beginner",
        equipment: "Cable Machine",
        primaryMuscles: ["Latissimus Dorsi"],
        secondaryMuscles: ["Biceps", "Trapezius"],
        duration: "30 min",
      },
      {
        id: "t-bar-rows",
        name: "T-Bar Rows",
        difficulty: "intermediate",
        equipment: "T-Bar",
        primaryMuscles: ["Latissimus Dorsi"],
        secondaryMuscles: ["Trapezius", "Biceps"],
        duration: "35 min",
      },
      {
        id: "single-arm-rows",
        name: "Single Arm Dumbbell Rows",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Latissimus Dorsi"],
        secondaryMuscles: ["Trapezius", "Biceps"],
        duration: "30 min",
      },
    ],
    triceps: [
      {
        id: "tricep-dips",
        name: "Tricep Dips",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Triceps"],
        secondaryMuscles: ["Shoulders", "Chest"],
        duration: "20 min",
      },
      {
        id: "skull-crushers",
        name: "Skull Crushers",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Triceps"],
        secondaryMuscles: [],
        duration: "25 min",
      },
      {
        id: "overhead-tricep-extension",
        name: "Overhead Tricep Extension",
        difficulty: "intermediate",
        equipment: "Dumbbells",
        primaryMuscles: ["Triceps"],
        secondaryMuscles: [],
        duration: "25 min",
      },
      {
        id: "tricep-pushdowns",
        name: "Tricep Pushdowns",
        difficulty: "beginner",
        equipment: "Cable Machine",
        primaryMuscles: ["Triceps"],
        secondaryMuscles: [],
        duration: "25 min",
      },
      {
        id: "close-grip-bench-press",
        name: "Close Grip Bench Press",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Triceps"],
        secondaryMuscles: ["Chest", "Shoulders"],
        duration: "35 min",
      },
    ],
    lowerBack: [
      {
        id: "deadlifts",
        name: "Deadlifts",
        difficulty: "advanced",
        equipment: "Barbell",
        primaryMuscles: ["Lower Back"],
        secondaryMuscles: ["Glutes", "Hamstrings", "Trapezius"],
        duration: "45 min",
      },
      {
        id: "good-mornings",
        name: "Good Mornings",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Lower Back"],
        secondaryMuscles: ["Glutes", "Hamstrings"],
        duration: "25 min",
      },
      {
        id: "hyperextensions",
        name: "Back Hyperextensions",
        difficulty: "beginner",
        equipment: "Hyperextension Bench",
        primaryMuscles: ["Lower Back"],
        secondaryMuscles: ["Glutes"],
        duration: "20 min",
      },
      {
        id: "superman",
        name: "Superman",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Lower Back"],
        secondaryMuscles: ["Glutes"],
        duration: "15 min",
      },
    ],
    glutes: [
      {
        id: "hip-thrusts",
        name: "Hip Thrusts",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Glutes"],
        secondaryMuscles: ["Hamstrings", "Lower Back"],
        duration: "30 min",
      },
      {
        id: "glute-bridges",
        name: "Glute Bridges",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Glutes"],
        secondaryMuscles: ["Hamstrings"],
        duration: "20 min",
      },
      {
        id: "clamshells",
        name: "Clamshells",
        difficulty: "beginner",
        equipment: "Resistance Band",
        primaryMuscles: ["Glutes"],
        secondaryMuscles: [],
        duration: "15 min",
      },
      {
        id: "single-leg-glute-bridges",
        name: "Single Leg Glute Bridges",
        difficulty: "intermediate",
        equipment: "Bodyweight",
        primaryMuscles: ["Glutes"],
        secondaryMuscles: ["Hamstrings"],
        duration: "25 min",
      },
    ],
    hamstrings: [
      {
        id: "romanian-deadlifts",
        name: "Romanian Deadlifts",
        difficulty: "intermediate",
        equipment: "Barbell",
        primaryMuscles: ["Hamstrings"],
        secondaryMuscles: ["Glutes", "Lower Back"],
        duration: "35 min",
      },
      {
        id: "leg-curls",
        name: "Leg Curls",
        difficulty: "beginner",
        equipment: "Machine",
        primaryMuscles: ["Hamstrings"],
        secondaryMuscles: [],
        duration: "25 min",
      },
      {
        id: "nordic-curls",
        name: "Nordic Curls",
        difficulty: "advanced",
        equipment: "Bodyweight",
        primaryMuscles: ["Hamstrings"],
        secondaryMuscles: [],
        duration: "20 min",
      },
      {
        id: "stiff-leg-deadlifts",
        name: "Stiff Leg Deadlifts",
        difficulty: "intermediate",
        equipment: "Dumbbells",
        primaryMuscles: ["Hamstrings"],
        secondaryMuscles: ["Glutes", "Lower Back"],
        duration: "30 min",
      },
    ],
    // NEW: Additional muscle groups
    rhomboids: [
      {
        id: "reverse-flyes",
        name: "Reverse Flyes",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Rhomboids"],
        secondaryMuscles: ["Trapezius", "Shoulders"],
        duration: "20 min",
      },
      {
        id: "prone-y-raises",
        name: "Prone Y Raises",
        difficulty: "beginner",
        equipment: "Dumbbells",
        primaryMuscles: ["Rhomboids"],
        secondaryMuscles: ["Trapezius", "Shoulders"],
        duration: "20 min",
      },
    ],
    serratus: [
      {
        id: "wall-slides",
        name: "Wall Slides",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Serratus Anterior"],
        secondaryMuscles: ["Shoulders"],
        duration: "15 min",
      },
      {
        id: "scapular-pushups",
        name: "Scapular Push-ups",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Serratus Anterior"],
        secondaryMuscles: ["Shoulders"],
        duration: "15 min",
      },
    ],
    // NEW: Cardio and conditioning
    cardio: [
      {
        id: "burpees",
        name: "Burpees",
        difficulty: "intermediate",
        equipment: "Bodyweight",
        primaryMuscles: ["Full Body"],
        secondaryMuscles: ["Cardiovascular"],
        duration: "20 min",
      },
      {
        id: "jump-rope",
        name: "Jump Rope",
        difficulty: "beginner",
        equipment: "Jump Rope",
        primaryMuscles: ["Calves"],
        secondaryMuscles: ["Cardiovascular"],
        duration: "30 min",
      },
      {
        id: "high-knees",
        name: "High Knees",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Hip Flexors"],
        secondaryMuscles: ["Cardiovascular"],
        duration: "15 min",
      },
      {
        id: "jumping-jacks",
        name: "Jumping Jacks",
        difficulty: "beginner",
        equipment: "Bodyweight",
        primaryMuscles: ["Full Body"],
        secondaryMuscles: ["Cardiovascular"],
        duration: "15 min",
      },
    ],
    // NEW: Compound movements
    compound: [
      {
        id: "thrusters",
        name: "Thrusters",
        difficulty: "intermediate",
        equipment: "Dumbbells",
        primaryMuscles: ["Full Body"],
        secondaryMuscles: ["Shoulders", "Legs"],
        duration: "30 min",
      },
      {
        id: "man-makers",
        name: "Man Makers",
        difficulty: "advanced",
        equipment: "Dumbbells",
        primaryMuscles: ["Full Body"],
        secondaryMuscles: ["Cardiovascular"],
        duration: "25 min",
      },
      {
        id: "turkish-getups",
        name: "Turkish Get-ups",
        difficulty: "advanced",
        equipment: "Kettlebell",
        primaryMuscles: ["Full Body"],
        secondaryMuscles: ["Core", "Shoulders"],
        duration: "30 min",
      },
    ],
  };